// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnvwdfnlnmrtcqpmojsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudndkZm5sbm1ydGNxcG1vanNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjYxMDUsImV4cCI6MjA2NTE0MjEwNX0.JfvXHQF6obNfUjXRa_D5QwelYgukdLHTiVowAuFTP7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);